<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>

    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <OptimizationPreference>Size</OptimizationPreference>
    <_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
  </PropertyGroup>

</Project>
